### ISSUE TITLE
Error while arguments is insufficient

### ISSUE THREAD

**Issue by mrasif** [mrinjamul/gtodo#3]
**Describe the bug**
Go routine error coming while executing insufficient command with arguments.

**To Reproduce**
1. Run any manipulation command without it's argument 
2. See error

**Expected behavior**
It should show help for that command, not the errors.

**Screenshots**
```sh
$ gtodo remove
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/mrinjamul/gtodo/cmd.removeRun(0x18edda0, 0x19213e0, 0x0, 0x0)
	/Users/asif/go/src/github.com/mrinjamul/gtodo/cmd/remove.go:40 +0x4f1
github.com/spf13/cobra.(*Command).execute(0x18edda0, 0x19213e0, 0x0, 0x0, 0x18edda0, 0x19213e0)
	/Users/asif/go/src/github.com/spf13/cobra/command.go:854 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x18ee040, 0x10433fa, 0x18b2960, 0xc000000180)
	/Users/asif/go/src/github.com/spf13/cobra/command.go:958 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/asif/go/src/github.com/spf13/cobra/command.go:895
github.com/mrinjamul/gtodo/cmd.Execute()
	/Users/asif/go/src/github.com/mrinjamul/gtodo/cmd/root.go:48 +0x31
main.main()
	/Users/asif/go/src/github.com/mrinjamul/gtodo/main.go:21 +0x20
```

**Comment by mrinjamul** [comment]
Fixed
